---
- name: Ensure Greengrass Group
  user:
    name: ggc_group
    system: yes
    state: present

- name: Ensure Greengrass User
  user:
    name: ggc_user
    system: yes
    state: present

- name: Ensure hard links are protected
  sysctl: 
    key: fs.protected_hardlinks
    value: 1
    state: present
    reload: yes

- name: Ensure soft links are protected
  sysctl: 
    key: fs.protected_symlinks
    value: 1
    state: present
    reload: yes

- name: Ensure cgroups are mounted
  script: cgroupfs-mount.sh
  args:
    creates: /usr/local/cgroupfs-mounted

- name: Ensure python 2.7 is installed
  apt:
    name: python2.7
    state: present

- name: Ensure sqlite3 is installed
  apt:
    name: sqlite3
    state: present

- name: Ensure nodesource gpg key is installed
  apt_key: "url={{ item }}"
  with_items:
    - "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
  tags:
    - nodejs

- name: Ensure nodesource repo is added to list to install nodejs
  apt_repository:
    repo: 'deb {{ item }}  {{ ansible_distribution_release }} main' 
    update_cache: yes
  with_items:
    - "https://deb.nodesource.com/node_6.x"
  tags:
    - nodejs

- name: Ensure the right version of nodejs is installed
  apt:
    name: nodejs
  tags:
    - nodejs

- name: Ensure that the Greengrass Core SDK is installed
  unarchive: 
    src: greengrass-linux-x86-64-1.3.0.tar.gz
    dest: /

- name: Ensure that the Greengrass config and certs are installed
  unarchive: 
    src: "{{ greengrass_core_setup_archive }}"
    dest: /greengrass

- name: Get the name of the private key file
  find: 
    paths: /greengrass/certs
    patterns: '*.private.key'
  register: keyfile

- name: Ensure that the private AWS IoT key is protected
  file:
    path: "{{ keyfile.files[0].path }}"
    mode: 0600

- name: Ensure that the Root CA cert is installed
  get_url:
    url: http://www.symantec.com/content/en/us/enterprise/verisign/roots/VeriSign-Class%203-Public-Primary-Certification-Authority-G5.pem
    dest: /greengrass/certs/root.ca.pem

- name: Ensure that the Greengrass service unit is defined
  copy:
    src: greengrass.service
    dest: /etc/systemd/system/greengrass.service
    owner: root
    group: root
    mode: 0644

- name: Ensure that the Greengrass daemon is running
  systemd: state=started name=greengrass daemon_reload=yes




